### ISSUE TITLE
"The required object/property "muleContext" is null" raised on retrieve when using it as object store for a cache scope

### ISSUE THREAD

**Issue by fireantology** [mulesoft/redis-connector#6]
Hi,
I'm using the connector as object store for a cache scope in this way.

```xml
<redis:config name="localRedis" host="localhost" port="6379" connectionTimeout="15000"/>
<ee:object-store-caching-strategy
		name="Caching_Strategy1" doc:name="Caching Strategy"
		keyGenerationExpression="#[payload]">
		<spring-object-store ref="localRedis" />
</ee:object-store-caching-strategy>
```

The set of the key works well but when I do the get I got the exception "muleContext" is null (full stack trace at the end of this ticket).
As I had prior experience in writing custom object store I tried to modify the retrieve method by simply setting the context on the retrieved event and it worked. Here a sample:

```java
    @Override
    public Serializable retrieve(final Serializable key) throws ObjectStoreException
    {
    	final MuleEvent sourceEvent = (MuleEvent) retrieve(key, getActualDefaultPartitionName());
       
        ((DefaultMuleMessage) sourceEvent.getMessage()).setMuleContext(muleContext);
        
	return sourceEvent;
    }
```
Now I don't know if this is the proper or clean solution and I'm open to fix this but not without really understending what I'm doing, that's why will be great if you could provide some guidance.

Thanks 

```
ERROR 2016-01-14 14:23:50,729 [[redis].HTTP_Listener_Configuration.worker.01] org.mule.exception.DefaultMessagingExceptionStrategy: 
********************************************************************************
Message               : The required object/property "muleContext" is null (java.lang.IllegalArgumentException). Message payload is of type: String
Type                  : org.mule.api.MessagingException
Code                  : MULE_ERROR--2
Payload               : /5
JavaDoc               : http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/MessagingException.html
********************************************************************************
Exception stack is:
1. The required object/property "muleContext" is null (java.lang.IllegalArgumentException)
  org.mule.DefaultMuleMessage:304 (null)
2. The required object/property "muleContext" is null (java.lang.IllegalArgumentException). Message payload is of type: String (org.mule.api.MessagingException)
  org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor:32 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/MessagingException.html)
********************************************************************************
Root Exception stack trace:
java.lang.IllegalArgumentException: The required object/property "muleContext" is null
	at org.mule.DefaultMuleMessage.setMuleContext(DefaultMuleMessage.java:304)
	at org.mule.DefaultMuleMessage.<init>(DefaultMuleMessage.java:194)
	at org.mule.DefaultMuleMessage.<init>(DefaultMuleMessage.java:297)
	at org.mule.DefaultMuleMessage.newThreadCopy(DefaultMuleMessage.java:1549)
	at org.mule.DefaultMuleEvent.newThreadCopy(DefaultMuleEvent.java:820)
	at com.mulesoft.mule.cache.eventcopier.DefaultMuleEventCopier.createEventCopy(DefaultMuleEventCopier.java:25)
	at com.mulesoft.mule.cache.AbstractCachingStrategy.processMessageWithCache(AbstractCachingStrategy.java:95)
	at com.mulesoft.mule.cache.AbstractCachingStrategy.process(AbstractCachingStrategy.java:74)
	at com.mulesoft.mule.cache.CachingMessageProcessor.process(CachingMessageProcessor.java:81)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:58)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.AsyncInterceptingMessageProcessor.process(AsyncInterceptingMessageProcessor.java:102)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:58)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.construct.DynamicPipelineMessageProcessor.process(DynamicPipelineMessageProcessor.java:54)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:58)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.interceptor.AbstractEnvelopeInterceptor.process(AbstractEnvelopeInterceptor.java:51)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:58)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.AbstractFilteringMessageProcessor.process(AbstractFilteringMessageProcessor.java:40)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:58)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.construct.AbstractPipeline$1.process(AbstractPipeline.java:109)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:58)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:58)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.construct.AbstractPipeline$3.process(AbstractPipeline.java:207)
	at org.mule.module.http.internal.listener.HttpMessageProcessorTemplate.routeEvent(HttpMessageProcessorTemplate.java:72)
	at org.mule.execution.AsyncResponseFlowProcessingPhase$1.process(AsyncResponseFlowProcessingPhase.java:52)
	at org.mule.execution.AsyncResponseFlowProcessingPhase$1.process(AsyncResponseFlowProcessingPhase.jav...
```

**Comment by ddossot** [comment]
Isn't this more a `cache` module issue than a `redis` one?

The implementation of `retrieve` in `redis` connector is [generic](https://github.com/mulesoft/redis-connector/blob/master/src/main/java/org/mule/module/redis/RedisModule.java#L1108-L1128) and thus doesn't know if what's stored is a `MuleMessage` or anything else.

**Comment by fireantology** [comment]
Hi,
I see now what you mean, the fact is that object store is in fact used also in other context and therefore should be left to the cache module the job of setting back the mule context. 
I suppose that for the moment I will end up copying and pasting the object store and modify it and I will try to contact Mule Support to see if there is already an open issue.
Thanks again
